[build-system]
requires = [  "setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-cpp-agent"
version = "0.0.1"
description = "A framework for building LLM based AI agents with llama-cpp-python."
readme = "ReadMe.md"
requires-python = ">=3.10"
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent" ]
[[project.authors]]
name = "Maximilian Winter"
email = "maximilian.winter.91@gmail.com"

[project.urls]
Homepage = "https://github.com/Maximilian-Winter/llama-cpp-agent"
"Bug Tracker" = "https://github.com/Maximilian-Winter/llama-cpp-agent/issues"
